export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST'
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS'
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL'


export const BOOK_DETAIL_REQUEST = 'BOOK_DETAIL_REQUEST'
export const BOOK_DETAIL_SUCCESS = 'BOOK_DETAIL_SUCCESS'
export const BOOK_DETAIL_FAIL = 'BOOK_DETAIL_FAIL'



export const FEATUREDBOOK_LIST_REQUEST = 'FEATUREDBOOK_LIST_REQUEST'
export const FEATUREDBOOK_LIST_SUCCESS = 'FEATUREDBOOK_LIST_SUCCESS'
export const FEATUREDBOOK_LIST_FAIL = 'FEATUREDBOOK_LIST_FAIL'